export type AuthErrorCode =
  | 'AUTH_PROVIDER_INVALID'
  | 'AUTH_PROVIDER_UNAVAILABLE'
  | 'AUTH_CODE_REJECTED'
  | 'AUTH_PROVIDER_TIMEOUT'
  | 'ACCESS_TOKEN_INVALID'
  | 'REFRESH_TOKEN_INVALID'
  | 'REFRESH_TOKEN_REUSED'
  | 'PHONE_AUTH_DISABLED'
  | 'PHONE_INVALID'
  | 'PHONE_REGION_UNSUPPORTED'
  | 'PHONE_CHALLENGE_INVALID'
  | 'PHONE_CHALLENGE_EXPIRED'
  | 'PHONE_CHALLENGE_ATTEMPTS_EXHAUSTED'
  | 'PHONE_RATE_LIMITED'
  | 'SMS_PROVIDER_FAILED'
  | 'SMS_PROVIDER_TIMEOUT'
  | 'SMS_PROVIDER_UNCERTAIN'
  | 'AUTH_ACCOUNT_UNAVAILABLE'
  | 'AUTH_IDENTITY_ALREADY_BOUND'
  | 'AUTH_LOGIN_METHOD_ALREADY_BOUND'
  | 'AUTH_VERIFICATION_GRANT_INVALID'
  | 'AUTH_STEP_UP_INVALID'
  | 'ACCOUNT_DELETE_UNAVAILABLE';

export class AuthError extends Error {
  constructor(
    public readonly code: AuthErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'AuthError';
  }
}
