export const LOG_REDACTION = {
  paths: [
    'req.headers.authorization',
    'req.body.authorizationCode',
    'req.body.codeVerifier',
    'req.body.refreshToken',
    'req.body.password',
    'res.headers["set-cookie"]',
    'authorizationCode',
    'codeVerifier',
    'refreshToken',
    'password',
    'passwordDigest',
    'roomPasswordPepper',
    'accessToken',
    'clientSecret',
    '*.authorizationCode',
    '*.codeVerifier',
    '*.refreshToken',
    '*.password',
    '*.passwordDigest',
    '*.roomPasswordPepper',
    '*.accessToken',
    '*.clientSecret',
  ],
  censor: '[REDACTED]',
};
