export const tokens = {
  color: {
    surface: '#FFF9F6',
    panel: '#ffffff',
    foreground: '#1D1B20',
    muted: '#787587',
    border: '#E0DEED',
    purple: '#6546EC',
    purpleSoft: '#F2EDFF',
    coral: '#FF6F70',
    peach: '#FFF0E8',
    peachBorder: '#F0DCD5',
    ambientGold: '#FFD65A',
    mint: '#E6FAF5',
    mintInk: '#137D75',
    blueSoft: '#E8F7FF',
    goldSoft: '#FFF4D8',
    error: '#BE3444',
  },
  // Original Rooms / Pilot V2 colors; kept separate from older screen accents.
  connection: {
    color: {
      panel: '#3A2B5A',
      muted: '#C9BEE5',
      ring: '#23C8BE',
      iconSurface: '#6247E8',
      actionSurface: '#EEE8FF',
      actionInk: '#5538D8',
    },
  },
  discovery: {
    color: {
      cardLavender: '#F2EDFF',
      cardBlue: '#E8F7FF',
      cardMint: '#E6FAF5',
      border: '#E8E2F2',
      ink: '#24212C',
      muted: '#777184',
      badgeAccent: '#5C42EC',
      available: '#138F83',
      unavailable: '#B95040',
      capacityOpen: '#FFF2CB',
      capacityPassword: '#D9F5F1',
      capacityFull: '#FFF1E8',
      filterSelected: '#EEE8FF',
      tabAccent: '#5538D8',
      tabMuted: '#96919F',
      countMuted: '#817B8C',
      navBorder: '#E9E6F0',
      confettiMint: '#23C8BE',
    },
  },
  space: {
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  radius: {
    lg: 24,
    md: 16,
    sm: 12,
  },
  font: {
    sm: 12,
    md: 16,
    xl: 28,
  },
} as const;
