export type RoomErrorCode =
  | 'ROOM_NOT_STARTED'
  | 'ROOM_CANCELLED'
  | 'APPOINTMENT_ALREADY_STARTED'
  | 'APPOINTMENT_BOOKING_CLOSED'
  | 'RESERVATION_CONFLICT'
  | 'RESERVATION_ALREADY_USED'
  | 'RESERVATION_OWNER_REQUIRED'
  | 'ROOM_RESERVED'
  | 'ROOM_ACCOUNT_RESTRICTED'
  | 'ROOM_HOST_REQUIRED'
  | 'ROOM_MEMBER_NOT_ACTIVE'
  | 'ROOM_INVITATION_REQUIRED'
  | 'ROOM_INVITATION_NOT_FOUND'
  | 'ROOM_INVITATION_TARGET_UNAVAILABLE'
  | 'ROOM_INVITATION_REQUEST_CONFLICT'
  | 'ROOM_SUCCESSOR_INVALID'
  | 'ROOM_HOST_RECONNECTING'
  | 'ROOM_OPERATION_CONFLICT'
  | 'PROFILE_REQUIRED'
  | 'AGE_RESTRICTED'
  | 'ROOM_MEMBERSHIP_REQUIRED'
  | 'ROOM_NOT_FOUND'
  | 'ROOM_SHARE_NOT_FOUND'
  | 'ROOM_SHARE_UNAVAILABLE'
  | 'ROOM_EXTENSION_NOT_AVAILABLE'
  | 'ROOM_EXTENSION_LIMIT'
  | 'ROOM_EXTENSION_REQUEST_CONFLICT'
  | 'ROOM_ENDED'
  | 'ROOM_FULL'
  | 'ROOM_PASSWORD_REQUIRED'
  | 'ROOM_PASSWORD_INVALID'
  | 'ROOM_RULES_NOT_ACCEPTED'
  | 'ROOM_SPEECH_CONSENT_REQUIRED'
  | 'ROOM_SPEECH_UNAVAILABLE'
  | 'POST_ROOM_KEYWORDS_CONSENT_REQUIRED'
  | 'POST_ROOM_KEYWORDS_UNAVAILABLE'
  | 'ROOM_CONFIGURATION_INVALID'
  | 'VALIDATION_FAILED';

export class RoomError extends Error {
  constructor(
    public readonly code: RoomErrorCode,
    message: string,
    public readonly details?: unknown,
  ) {
    super(message);
    this.name = 'RoomError';
  }
}
