services:
  postgres-dev:
    image: postgres:17.6-alpine
    environment:
      POSTGRES_DB: slogan
      POSTGRES_PASSWORD: slogan
      POSTGRES_USER: slogan
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - slogan-postgres-dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U slogan -d slogan']
      interval: 2s
      timeout: 3s
      retries: 20
  redis-dev:
    image: redis:7.4-alpine
    ports:
      - '127.0.0.1:6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      timeout: 3s
      retries: 20
    volumes:
      - slogan-redis-dev:/data

volumes:
  slogan-postgres-dev:
  slogan-redis-dev:
